service: frontend
runtime: nodejs22
instance_class: F1

env_variables:
  VITE_FIREBASE_API_KEY: "AIzaSyB0zksQcRRTeMr7egZ9UD_kqursHpDANOk"
  VITE_FIREBASE_AUTH_DOMAIN: "eci-portal-473011.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "eci-portal-473011"
  VITE_FIREBASE_STORAGE_BUCKET: "eci-portal-473011.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "393295958747"
  VITE_FIREBASE_APP_ID: "1:393295958747:web:9dc3b0012fbc5c9fd232fe"
  VITE_FIREBASE_MEASUREMENT_ID: "G-BGV3L2KXJJ"
  VITE_SERVER_URL: "https://bhasantar-ui-and-llm.as.r.appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  # Serve static assets from the 'assets' folder
  - url: /assets
    static_dir: dist/assets

  - url: /(.*\.js)
    static_files: dist/\1
    upload: dist/.*\.js

  - url: /(.*\.css)
    static_files: dist/\1
    upload: dist/.*\.css

  - url: /(.*\.(ico|png|svg|jpg))
    static_files: dist/\1
    upload: dist/.*\.(ico|png|svg|jpg)

  # Catch-all handler to serve index.html for other routes
  - url: /.* 
    static_files: dist/index.html
    upload: dist/index.html
