runtime: nodejs22
entrypoint: npm start

env: standard

instance_class: F1

env_variables:
  NODE_ENV: production
  GOOGLE_APPLICATION_CREDENTIALS: 'eci-portal-473011-firebase-adminsdk-fbsvc-c562e53363.json'  
  GCP_PROJECT_ID: 'eci-portal-473011'  # Your Google Cloud project ID
  GCS_BUCKET_NAME: 'eci_storage'  # Your Cloud Storage bucket name

  FIREBASE_TYPE: "service_account"
  FIREBASE_PROJECT_ID: "eci-portal-473011"
  FIREBASE_PRIVATE_KEY_ID: "c562e53363d65569931a99eeb0ed7420cce85790"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDU0KRKP9OILun2\nJr1AA0WdVOBV9Xh49htaRkyBc7Plzcl/udxhlgX63x3tiama4dKbmkeaKIKj+e/l\nCw3GQKv7rg6zqobgLWRZ1o1U+lDvW4rURTPzrsAFI0Fm7Bb8f5Yfk7ReRrAbIMlc\nGnkxM43JuZDCa1xm1PlgFbIKa2mXc2SDZDOtsSef0f5wMrKlQ5cpNmADGvhJzVnC\niM5uAHVJbagLbD+lpu8l2C49FVABCKEZpP7MaNgFUYyb5uA68TIl9lZ7CYxDqHfD\n7uZX0DkOjir+DyDlkcKFYc22M3LfiRa7WxvAWEjcRSTk7W+tO0Y3DSSv1pD9wDJD\nSWzOtxb9AgMBAAECggEAXFhk0es8SP3CfBN3T42b6Zdo+SPZMPPqDpQuooWobHGN\nnCT0YkwNMD0c6XQw6opPL0IVC+nENo8/762KPprVhhKTQpcei6xmvS0CivtLn3Gj\nnlShJH6RyCjyOkz79HkQlYcsXzRhOoRRm+vI5vat8fjZveOEZwLHa1A+v5K4cQTQ\n4q/cbKgFVogOySV9ibyhSKAWovpeRH3BcG/yl9o7Y2XMS8742HsnJHk3eJOqsks9\nFkSWx3qGdSDb1boeNOAOeSJeBQfpK5Q2B9Ssye79WqwJuLD1FI6GuW2ckanSEWCn\ndfA5hj3ZzNQ+c8J2zxaEwJb92+CGeSdAHhV6VAHDKQKBgQDtNqMB+VwqYBx2s+2J\n8zFEqKkF3fiuqCUmb3XesnBwOBFkUI7QnomWR1LOSbxwf4alK4P+abs5s1PcZtzi\nBbCDC61UTqqSvbFD3afvAEcSLVuQUr3Nn2zYhX/jRvSjtxQhnYmdI0eXEyd5JGXS\ndt+TWgMjmYErIPgCi1brwqZE7wKBgQDlq1dkZjVR8/1IWajJkamnxrOirIP8C04E\nyEACZ5olGbQgkk7xi1Yr4WFimVo/d83b3o7sy+Hd6e79Ad8yqbf8IaQrttKvYxjo\n7h7iLoGmjLXCplMORMwkdY3a0EQNAl8qPb4OFXbQMDmQ0WQtTZJOdnRCodya+jQA\nWxX8hhQa0wKBgQCO6tUpMlCqIz/i8KLT81aitC8pnsPejuXbE1pjswR1SAKKetKg\ntHPWu+AS82/6I4s+5knfNVqc+AM1ji/UaXMgcR+b5M12HZ24cspj/7nSJMu+12sN\ngNj2VvBnQW/RV1NksWKg7wmJ5vtoTFqghAhN4fR0NV8SWgmylrrmzl6YtwKBgQDd\nuKVc2sNdA+SghVZKimI0A8MGJ/AfUjaWrVAGQkhwyri3vSeTTsX5BNOEYbHblehZ\n/CkU99ts5lt/S+BTQ7/IHB4myY/qHAw/SyrrhqRJyovqh7GlE8vU4tv4w5j+yixf\nVk31wMj8QaJBabSBe+Lj9r1UWnjj8Opk8YpvSG1+WwKBgQDpp8o01jbnpG99cQ78\nuZtFXay+vfvKoJDaAKbffUs/VJzF6r2kLQDY4Qf26lknJeZ+P6gufo5MuETune7K\nfmg26RCGAI/4wsBfPDvHCE4baCgl/PQ0mKI/bNCII+pCGMMpgJvmcLEIx097bMWf\nbu9u2PVjC/nH3MOistR5GF2+rw==\n-----END PRIVATE KEY-----\n"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@eci-portal-473011.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID: "104603960540679647197"
  FIREBASE_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  FIREBASE_TOKEN_URI: "https://oauth2.googleapis.com/token"
  FIREBASE_AUTH_PROVIDER_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  FIREBASE_CLIENT_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40eci-portal-473011.iam.gserviceaccount.com"
  FIREBASE_UNIVERSE_DOMAIN: "googleapis.com"

  PORT: 5566
  FRONTEND_URL: "http://localhost:5173"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: auto
